
CREATE TABLE personas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activated bool NOT NULL,
	apellidos varchar(255) NULL,
	fecha_nacimiento timestamp(6) NULL,
	identificacion varchar(255) NULL,
	nombres varchar(255) NULL,
	CONSTRAINT personas_pkey PRIMARY KEY (id)
);



CREATE TABLE rol_opciones (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activated bool NOT NULL,
	nombre_opcion varchar(255) NULL,
	CONSTRAINT rol_opciones_pkey PRIMARY KEY (id)
);


CREATE TABLE roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activated bool NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);



CREATE TABLE roles_rol_opciones (
	id_opcion int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT ukag3f2gpuf2beij16wlyr008ix UNIQUE (id_opcion, role_id),
	CONSTRAINT fkhpbmeb9l4mbhp6usxe93hprm8 FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT fkljd9pagfhyejq8l7h0te40uio FOREIGN KEY (id_opcion) REFERENCES public.rol_opciones(id)
);



CREATE TABLE usuarios (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	"password" varchar(255) NULL,
	session_active bool NULL,
	status varchar(255) NULL,
	username varchar(255) NULL,
	persona_id int8 NULL,
	CONSTRAINT ukl5dltx5is9uxuo22lofxowqhs UNIQUE (persona_id),
	CONSTRAINT usuarios_pkey PRIMARY KEY (id),
	CONSTRAINT fkoesedii3ntyaw1650vh2d9jso FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);



CREATE TABLE sessions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activated bool NOT NULL,
	fecha_cierre timestamp(6) NULL,
	fecha_ingreso timestamp(6) NULL,
	usuarios_id_usuario int8 NULL,
	CONSTRAINT sessions_pkey PRIMARY KEY (id),
	CONSTRAINT fk4uvxkx7x1p0d57m7lum38ycq8 FOREIGN KEY (usuarios_id_usuario) REFERENCES public.usuarios(id)
);



CREATE TABLE users_roles (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT ukq3r1u8cne2rw2hkr899xuh7vj UNIQUE (user_id, role_id),
	CONSTRAINT fkj6m8fwv7oqv74fcehir1a9ffy FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT fkn041pceibmgxc7f9hcb95tm13 FOREIGN KEY (user_id) REFERENCES public.usuarios(id)
);


INSERT INTO roles (activated,"name") VALUES
	 (true,'ROLE_ADMIN'),
	 (true,'ROLE_USER');

INSERT INTO personas
(activated, apellidos, fecha_nacimiento, identificacion, nombres)
VALUES(true, 'admin', '2000-10-10 00:00:00.000', '9999999999', 'admin');


INSERT INTO usuarios
(email, "password", session_active, status, username, persona_id)
VALUES('xyz@mail.com', '$2a$10$5KQQcWpNA033OrT/bb6IRePw7a6ldGewERhqiPrQK8MBEFPEB7f9a', true, NULL, 'admin', 1);


INSERT INTO users_roles
(user_id, role_id)
VALUES(1, 1);

---SESSIONS STORED PROCEDURES

CREATE OR REPLACE PROCEDURE proc_create_session(p_user_id sessions.usuarios_id_usuario%type)
as $$
declare
    v_fecha_ingreso sessions.fecha_ingreso%type;
begin
    v_fecha_ingreso:= CURRENT_TIMESTAMP;
    INSERT INTO sessions (activated, fecha_ingreso, usuarios_id_usuario)
        VALUES (true, v_fecha_ingreso, p_user_id);
EXCEPTION
    when others then
        RAISE notice 'Error';
end;
$$ LANGUAGE plpgsql;


---


CREATE OR REPLACE PROCEDURE proc_cerrar_session(p_id sessions.id%type)
as $$
declare
    v_fecha_cierre sessions.fecha_cierre%type;
begin
    v_fecha_cierre:= CURRENT_TIMESTAMP;
    UPDATE sessions set fecha_cierre = v_fecha_cierre
        WHERE sessions.id = p_id;
EXCEPTION
    when others then
        RAISE notice 'Error';
end;
$$ LANGUAGE plpgsql;
